### ISSUE TITLE
Feature request: Add support for maxResults param (>50 issues)

### ISSUE THREAD

**Issue by mikeparker** [DanielHilton/jira-jql-search#1]
Right now this maxes out at 50 issues.

**Comment by DanielHilton** [comment]
I've not touched this in a while, but it does look like it's due an update in more ways than one.
https://jira-node.github.io/class/src/jira.js~JiraApi.html#instance-method-searchJira

I presume you mean this, I'll see what I can do

**Comment by DanielHilton** [comment]
> Right now this maxes out at 50 issues.

v0.2.0 includes this, could you test? i don't have a JIRA instance of my own to test with. if you find any issues i'll fix them or you can raise a PR 👌🏻

**Comment by mikeparker** [comment]
Sorry for the delay - this works as expected, thanks! 🥳
